# vim:ft=conf
# @author nate zhou
# @since 2023,2024,2025
# newsboat/colors.conf
# @modified by NeoJuliet (2026)

color background          white   black
color listnormal          white   black
color listfocus           black   white   bold
color listnormal_unread   magenta black
color listfocus_unread    magenta white   bold
color info                blue    black   bold
color article             white   black
