# vim:ft=lf
# lf/bindings.conf
# @author nate zhou
# since 2025
# disable default mappings
# @modified by NeoJulieta (2026)

map ','
map '.'
map "'"
map '"'
map 'm'
map 't'
map '['
map ']'
map 'r'
map 'sa'
map 'se'
map 'y'

map * tag-toggle
# open_with is user-defined in ./rifle.conf
map o open_with

# e for editting with default editor
map e $$EDITOR "$f"

map <enter> :shell

map S :calcdirsize

map H     jump-prev
map L     jump-next

map J :{{
    toggle
    down
}}
map K :{{
    toggle
    up
}}

map T &{{
    kitty --directory="$PWD" --hold --execute lf
}}

# reload lf configure
map .r source ~/.config/lf/lfrc

map r set reverse!

# a for rename
map a :rename

# U for checking size
map U !cdu -dh -s "$fx"

# f for fliter
map f :filter

map w $$SHELL
map ` !true

map tr cd /
map te cd /etc
map tu cd /usr
map ts cd ~/share
map th cd ~
map tc cd ~/.config
map tl cd ~/.local
map td cd ~/down
map tD cd ~/docs
map tp cd ~/media/pics

# *_sort is user-defined in ./command.conf
map sb birth_sort
map sc change_sort
map sn name_sort
map ss size_sort
map st time_sort

# info is user-defined in ./command.conf
map i file_info
map mm media_info
map mf file_mimetype
map mF files_mimetype
map mc convert

# extrat is user-defined in ./command.conf
map xx extract

map yy copy
map yp path_copy
map yn name_copy

map zp toggle-preview
