# disable default mappings
map ','
map '.'
map "'"
map '"'
map 'm'
map 't'
map '['
map ']'
map 'r'
map 'sa'
map 'se'
map 'y'

map * tag-toggle
# open_with is user-defined in ./rifle.conf
map o open_with

# e for editting with default editor
map e $$EDITOR "$f"

map H     jump-prev
map L     jump-next

map J : {{
    toggle
    down
}}
map K : {{
    toggle
    up
}}
# reload lf configure
map .r source ~/.config/lf/lfrc

map r set reverse!

# a for rename
map a :rename

# U for checking size
map U !cdu -dh -s $fx

# f for fliter
map f :filter

map w $$SHELL
map ` !true

map tr cd /
map te cd /etc
map tu cd /usr
map td cd ~/Docs
map tl cd ~/.local
map th cd ~
map tc cd ~/.config
map tD cd ~/Downloads
map tn cd ~/Notes

# *_sort is user-defined in ./command.conf
map sb birth_sort
map sc change_sort
map sn name_sort
map ss size_sort
map st time_sort

map mi $mediainfo -l $f | less -i
map me $exiftool $f | less -i
map mf %file -Lb --mime-type $f | tr '\n' ' '
map mF $file -L --mime-type $fx | less -i
map mc $iconv -f GBK -t UTF-8 $f | less -i

# extrat is user-defined in ./command.conf
map xx extract

map yy copy
map yp path_copy
map yn name_copy

map zp toggle-preview
