# vim:ft=lf
# @author nate zhou
# @since 2025,2026
# lf/rifle.conf - file opener
# @modified by NeoJuliet (2026)

cmd open &{{
    term="footclient"
    case "$(file --mime-type -Lb "$f")" in
        image/*)
            ~/.local/bin/swayimg-lf "$f"
            ;;
        video/*)
            mpv --wayland-app-id=temp-mpv -- "$f"
            ;;
        audio/*)
            mpv -- "$f"
            ;;
        application/pdf|application/epub+zip)
            zathura -- "$f"
            ;;
        application/vnd.openxmlformats-officedocument.*|\
        application/msword|\
        application/vnd.ms-excel)
            libreoffice -- "$f"
            ;;
        text/*|inode/x-empty)
            lf -remote "send $id \$$EDITOR -p \$fx"
            ;;
        application/zip|\
        application/x-tar|\
        application/x-7z-compressed|\
        application/x-rar)
            xdg-open "$f"
            ;;
        application/x-executable|application/x-pie-executable)
            "$f"
            ;;
        *)
            xdg-open "$f"
            ;;
    esac
}}

cmd open_with %{{
    ~/.local/bin/openwith "$f" "$id"
}}
