# vim:ft=lf
# @author nate zhou
# @since 2025,2026
# lf/rifle.conf - file opener
# @modified by NeoJuliet (2026)

cmd open &{{
    term="footclient"

    case $(file --mime-type -Lb $f) in
        image/*)
            swayimg "$f"
            ;;
        video/*)
            mpv "$f"
            ;;
        audio/*)
            mpv "$f"
            ;;
        */pdf|*/epub*)
            zathura $f
            ;;
        text/*|inode/x-empty)
            lf -remote "send $id \$$EDITOR -p \$fx"
            ;;
        application/*)
            lf -remote "send $id \$$EDITOR -p \$fx"
            ;;
    esac
}}

cmd open_with %{{
    ~/.local/bin/openwith "$f" "$id"
}}
