[main]
# Layout
icon-theme=Papirus-Dark
font=JetBrainsMono Nerd Font:size=10
prompt="$ "
terminal=kitty -e
anchor=bottom-right
width=40
lines=5
horizontal-pad=4
vertical-pad=4
inner-pad=0
line-height=15
letter-spacing=0

# Search
fields=name,exec
match-mode=fzf
sort-result=yes

[colors]
prompt=ffffffff
background=282a36ee
text=ffffffff
match=fc0313ff
selection=DCD0FFff
selection-text=282a36ff
selection-match=fc0313ff
border=DCD0FFff


[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
 prev=Up Control+p
 next=Down Control+n

[border]
width=2
radius=0
